services:
  worker-service:
    build:
      context: .
      args:
        SERVICE: worker-service
    ports:
      - "8081:8081"

  api-service:
    build:
      context: .
      args:
        SERVICE: api-service
    ports:
      - "8080:8080"
    environment:
      WORKER_BASE_URL: http://worker-service:8081
    depends_on:
      - worker-service
