server:
  port: 8081

spring:
  datasource:
    url: "${DB_URL:jdbc:postgresql://localhost:5432/jobqueue}"
    username: "${DB_USER:jobqueue}"
    password: "${DB_PASSWORD:jobqueue}"
  sql:
    init:
      mode: always